#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2020-present Fewtarius

echo "Reached scripts/build_distro"
#bash -c 'read -n 1 -s -r'

# Check ARCH parameter
echo "Checking ARCH parameter"
if [ -z "${ARCH}" ]
then
  echo "export ARCH before building." >&2
  exit 1
fi

# Declare project/device info
echo "Declaring project/device info"
#export DISTRO=AmberELEC
export DISTRO=RetroPixel
export PROJECT=Rockchip

echo "Building ${DISTRO} for ${DEVICE}"

# Create the target folder if it doesn't exist
echo "Checking whether target folder exists"
if [ ! -d "target" ]
then
  mkdir target
fi

# Clean a few packages to ensure the build date and version are updated
#for package in amberelec emulationstation retroarch retrorun lib32 u-boot
#for package in linux

# Clean the packages declared below to ensure the build date and version are updated.
#for package in linux
#for package in u-boot
#do
#  ./scripts/clean ${package}
#done

echo "Checking ARCH type"
if [ "${ARCH}" == "aarch64" ]
then
	echo "About to run make image"
	#bash -c 'read -n 1 -s -r'
  make image
elif [ "${ARCH}" == "arm" ]
then
  # Only build the 32bit packages that we need rather than the whole image
  # to speed up the build process and save disk space.
  for package in build-lib32
  do
    scripts/build ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  
    scripts/install ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  done
fi

if [ ! $? == 0 ]
then
  echo "Build failed..exiting."
  exit 1
fi

echo "Creating release files"
if [ "${ARCH}" == "aarch64" ]
then
  if [ -d "release/${ARCH}/RPPOCKET" ]
  then
    rm -rf "release/${ARCH}/RPPOCKET"
  fi
mkdir -p release/${ARCH}/RPPOCKET
mv target/* "release/${ARCH}/${DEVICE}/"
fi
